#!/usr/bin/env bash
set -euo pipefail

# Generates index.yaml from plugins.meta.yaml + built plugin artifacts.
#
# Usage: VERSION=v2026.02.18-abc1234 ./scripts/generate-index.sh
#
# Expects:
#   - plugins.meta.yaml in repo root (static metadata)
#   - dist/plugins/*.so.tar.gz (built artifacts with checksums)
#   - VERSION env var (release tag, e.g. v2026.02.18-abc1234)
#   - yq installed (https://github.com/mikefarah/yq)

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
META_FILE="$REPO_ROOT/plugins.meta.yaml"
INDEX_FILE="$REPO_ROOT/index.yaml"
DIST_DIR="$REPO_ROOT/dist/plugins"

if [[ -z "${VERSION:-}" ]]; then
  echo "ERROR: VERSION env var is required" >&2
  exit 1
fi

if [[ ! -f "$META_FILE" ]]; then
  echo "ERROR: $META_FILE not found" >&2
  exit 1
fi

# Strip leading 'v' for the version used in index
VER_NO_PREFIX="${VERSION#v}"

# Read defaults from meta
AUTHOR=$(yq '.defaults.author' "$META_FILE")
LICENSE=$(yq '.defaults.license' "$META_FILE")
URL=$(yq '.defaults.url' "$META_FILE")

# Start writing index.yaml
cat > "$INDEX_FILE" << 'HEADER'
# AUTO-GENERATED by scripts/generate-index.sh — do not edit manually.
# Source of truth for static metadata: plugins.meta.yaml
# Versions and checksums are computed from release artifacts.

api_version: v1

download_url_template: "https://github.com/hatembentayeb/omo/releases/download/v{{version}}/{{name}}-v{{version}}-{{os}}-{{arch}}.so.tar.gz"

plugins:
HEADER

# Iterate over each plugin in meta
PLUGIN_NAMES=$(yq '.plugins | keys | .[]' "$META_FILE")

for name in $PLUGIN_NAMES; do
  DESC=$(yq ".plugins.\"$name\".description" "$META_FILE")
  TAGS_JSON=$(yq -o=json ".plugins.\"$name\".tags" "$META_FILE")
  ARCH_JSON=$(yq -o=json '.defaults.arch' "$META_FILE")

  # Compute SHA256 for each arch
  SHA_AMD64=""
  SHA_ARM64=""

  AMD64_FILE="$DIST_DIR/${name}-${VERSION}-linux-amd64.so.tar.gz"
  ARM64_FILE="$DIST_DIR/${name}-${VERSION}-linux-arm64.so.tar.gz"

  if [[ -f "$AMD64_FILE" ]]; then
    SHA_AMD64=$(sha256sum "$AMD64_FILE" | awk '{print $1}')
  else
    echo "WARNING: $AMD64_FILE not found, skipping amd64 checksum for $name" >&2
  fi

  if [[ -f "$ARM64_FILE" ]]; then
    SHA_ARM64=$(sha256sum "$ARM64_FILE" | awk '{print $1}')
  else
    echo "WARNING: $ARM64_FILE not found, skipping arm64 checksum for $name" >&2
  fi

  # Write plugin entry
  cat >> "$INDEX_FILE" << ENTRY
  - name: "$name"
    version: "$VER_NO_PREFIX"
    description: "$DESC"
    author: "$AUTHOR"
    license: "$LICENSE"
    url: "$URL"
    tags: $TAGS_JSON
    arch: $ARCH_JSON
ENTRY

  # Add checksums block only if we have at least one
  if [[ -n "$SHA_AMD64" || -n "$SHA_ARM64" ]]; then
    echo "    checksums:" >> "$INDEX_FILE"
    if [[ -n "$SHA_AMD64" ]]; then
      echo "      linux-amd64: \"$SHA_AMD64\"" >> "$INDEX_FILE"
    fi
    if [[ -n "$SHA_ARM64" ]]; then
      echo "      linux-arm64: \"$SHA_ARM64\"" >> "$INDEX_FILE"
    fi
  fi

  echo "" >> "$INDEX_FILE"
done

PLUGIN_COUNT=$(echo "$PLUGIN_NAMES" | wc -w)
echo "Generated $INDEX_FILE with $PLUGIN_COUNT plugins (version: $VER_NO_PREFIX)"
