#!/usr/bin/env bash
set -euo pipefail

# Generates index.yaml from plugins.meta.yaml + built plugin artifacts.
#
# Usage: VERSION=v2026.02.18-abc1234 ./scripts/generate-index.sh
#
# Expects:
#   - plugins.meta.yaml in repo root (static metadata)
#   - dist/plugins/{name}-{VERSION}-{os}-{arch}.tar.gz (RPC plugin executables)
#   - VERSION env var (release tag, e.g. v2026.02.18-abc1234)
#   - yq installed (https://github.com/mikefarah/yq)

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
META_FILE="$REPO_ROOT/plugins.meta.yaml"
INDEX_FILE="$REPO_ROOT/index.yaml"
DIST_DIR="$REPO_ROOT/dist/plugins"

# Platforms released by .github/workflows/release.yml
PLATFORMS=(
  linux-amd64
  linux-arm64
  darwin-amd64
  darwin-arm64
  windows-amd64
)

if [[ -z "${VERSION:-}" ]]; then
  echo "ERROR: VERSION env var is required" >&2
  exit 1
fi

if [[ ! -f "$META_FILE" ]]; then
  echo "ERROR: $META_FILE not found" >&2
  exit 1
fi

# Strip leading 'v' for the version used in index
VER_NO_PREFIX="${VERSION#v}"

# Read defaults from meta (raw strings; works on mikefarah yq v4 and python yq v3)
AUTHOR=$(yq -r '.defaults.author' "$META_FILE")
LICENSE=$(yq -r '.defaults.license' "$META_FILE")
URL=$(yq -r '.defaults.url' "$META_FILE")

# Start writing index.yaml
cat > "$INDEX_FILE" << 'HEADER'
# AUTO-GENERATED by scripts/generate-index.sh — do not edit manually.
# Source of truth for static metadata: plugins.meta.yaml
# Versions and checksums are computed from release artifacts.
# Artifacts are RPC plugin executables (hashicorp/go-plugin).

api_version: v1

download_url_template: "https://github.com/hatembentayeb/omo/releases/download/v{{version}}/{{name}}-v{{version}}-{{os}}-{{arch}}.tar.gz"

plugins:
HEADER

# Iterate over each plugin in meta (strip quotes for yq v3 compatibility)
PLUGIN_NAMES=$(yq '.plugins | keys | .[]' "$META_FILE" | tr -d '"')

for name in $PLUGIN_NAMES; do
  # -r (raw) on mikefarah/yq v4 and python yq v3
  DESC=$(yq -r ".plugins.\"$name\".description" "$META_FILE")
  if TAGS=$(yq -o=json -I=0 ".plugins.\"$name\".tags" "$META_FILE" 2>/dev/null); then
    :
  else
    TAGS=$(yq -c ".plugins.\"$name\".tags" "$META_FILE")
  fi
  if ARCH=$(yq -o=json -I=0 '.defaults.arch' "$META_FILE" 2>/dev/null); then
    :
  else
    ARCH=$(yq -c '.defaults.arch' "$META_FILE")
  fi

  # Write plugin entry
  cat >> "$INDEX_FILE" << ENTRY
  - name: "$name"
    version: "$VER_NO_PREFIX"
    description: "$DESC"
    author: "$AUTHOR"
    license: "$LICENSE"
    url: "$URL"
    tags: $TAGS
    arch: $ARCH
ENTRY

  # Collect checksums for every released platform that has an artifact.
  checksum_lines=()
  for platform in "${PLATFORMS[@]}"; do
    artifact="$DIST_DIR/${name}-${VERSION}-${platform}.tar.gz"
    if [[ -f "$artifact" ]]; then
      sha=$(sha256sum "$artifact" | awk '{print $1}')
      checksum_lines+=("      ${platform}: \"${sha}\"")
    else
      echo "WARNING: $artifact not found, skipping ${platform} checksum for $name" >&2
    fi
  done

  if [[ ${#checksum_lines[@]} -gt 0 ]]; then
    echo "    checksums:" >> "$INDEX_FILE"
    printf '%s\n' "${checksum_lines[@]}" >> "$INDEX_FILE"
  fi

  echo "" >> "$INDEX_FILE"
done

PLUGIN_COUNT=$(echo "$PLUGIN_NAMES" | wc -w)
echo "Generated $INDEX_FILE with $PLUGIN_COUNT plugins (version: $VER_NO_PREFIX)"
